/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    IndexerRegistry: {
      address: "0x3be578a72d1c4ffdbb2aa2418a7fb749bcdba313",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "usdc",
              type: "address",
              internalType: "address",
            },
            {
              name: "clawd",
              type: "address",
              internalType: "address",
            },
            {
              name: "treasury",
              type: "address",
              internalType: "address",
            },
            {
              name: "router",
              type: "address",
              internalType: "address",
            },
            {
              name: "clawdUsdcPool",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BASE_SLASH_COOLDOWN",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BASE_SLASH_PCT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BASE_WITHDRAWAL_COOLDOWN",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BOOST_SLASH_PCT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BOOST_WITHDRAWAL_COOLDOWN",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CLAWD",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CLAWD_USDC_V3_POOL",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "DISPUTE_COUNTER_STAKE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "DISPUTE_RESPONSE_SECS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "DISPUTE_WINDOW_SECS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "DOMAIN_SEPARATOR",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "EIP4788_BEACON_ROOTS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_BATCH_SIZE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_BASE_STAKE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_QUERY_FEE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "RESOLUTION_BUFFER",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "REVEAL_WINDOW",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SETTLEMENT_TYPEHASH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TREASURY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TWAP_WINDOW",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "UNISWAP_V3_ROUTER",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "USDC",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "boostUnlockTime",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "unlockTime",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "buybackReserveUSDC",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "commitResponse",
          inputs: [
            {
              name: "disputeId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "proofHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "consumerNonceUsed",
          inputs: [
            {
              name: "consumer",
              type: "address",
              internalType: "address",
            },
            {
              name: "nonce",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "used",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "consumerSettlements",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "consumer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "settlementCount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "depositBaseStake",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deregister",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "disputerRecords",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "lossCount",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "lastLossAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "multiplier",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "disputes",
          inputs: [
            {
              name: "disputeId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "disputer",
              type: "address",
              internalType: "address",
            },
            {
              name: "indexer",
              type: "address",
              internalType: "address",
            },
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "counterStake",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "atRiskBoost",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "openedAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "commitHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "committedAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "state",
              type: "uint8",
              internalType: "enum IndexerRegistry.DisputeState",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "executeBuyback",
          inputs: [
            {
              name: "minClawdOut",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "clawdReceived",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "indexerOpenDisputeCount",
          inputs: [
            {
              name: "indexer",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "indexers",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "baseStake",
              type: "uint128",
              internalType: "uint128",
            },
            {
              name: "registrationCount",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "deregisteredAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "lastSlashAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "slashCount",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "openDispute",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "disputeId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "openDisputeCount",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "register",
          inputs: [
            {
              name: "target",
              type: "address",
              internalType: "address",
            },
            {
              name: "eventSig",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "boost",
              type: "uint96",
              internalType: "uint96",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registerBatch",
          inputs: [
            {
              name: "regs",
              type: "tuple[]",
              internalType: "struct IndexerRegistry.RegisterInput[]",
              components: [
                {
                  name: "targetContract",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "eventSigHash",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "boostStake",
                  type: "uint96",
                  internalType: "uint96",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registrations",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "targetContract",
              type: "address",
              internalType: "address",
            },
            {
              name: "boostStake",
              type: "uint96",
              internalType: "uint96",
            },
            {
              name: "eventSigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "registeredAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "deregisteredAt",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "indexer",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "reputationScore",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rescueToken",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "resolveExpiredDispute",
          inputs: [
            {
              name: "disputeId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "revealResponse",
          inputs: [
            {
              name: "disputeId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "proofData",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settleQuery",
          inputs: [
            {
              name: "s",
              type: "tuple",
              internalType: "struct IndexerRegistry.SettlementData",
              components: [
                {
                  name: "indexer",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "regId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "queryCount",
                  type: "uint32",
                  internalType: "uint32",
                },
                {
                  name: "totalFeeUSDC",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "consumerNonce",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
            {
              name: "sig",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawBaseStake",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawBoost",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BaseStakeSlashed",
          inputs: [
            {
              name: "indexer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "remaining",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BuybackExecuted",
          inputs: [
            {
              name: "usdcIn",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "clawdBurned",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Deregistered",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DisputeOpened",
          inputs: [
            {
              name: "disputeId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "disputer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "regId",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "DisputeResolved",
          inputs: [
            {
              name: "disputeId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "winner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "QuerySettled",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "consumer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "queryCount",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
            {
              name: "totalFee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Registered",
          inputs: [
            {
              name: "regId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "indexer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "target",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "eventSig",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "boost",
              type: "uint96",
              indexed: false,
              internalType: "uint96",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ResponseCommitted",
          inputs: [
            {
              name: "disputeId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyRegistered",
          inputs: [],
        },
        {
          type: "error",
          name: "BatchTooLarge",
          inputs: [],
        },
        {
          type: "error",
          name: "CannotRescueProtocolToken",
          inputs: [],
        },
        {
          type: "error",
          name: "CooldownNotElapsed",
          inputs: [],
        },
        {
          type: "error",
          name: "DisputeNotResolvable",
          inputs: [],
        },
        {
          type: "error",
          name: "FeeBelowMinimum",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientBaseStake",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidAmount",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSignature",
          inputs: [],
        },
        {
          type: "error",
          name: "MinOutNotMet",
          inputs: [],
        },
        {
          type: "error",
          name: "NonceAlreadyUsed",
          inputs: [],
        },
        {
          type: "error",
          name: "NotIndexer",
          inputs: [],
        },
        {
          type: "error",
          name: "OpenRegistrationsExist",
          inputs: [],
        },
        {
          type: "error",
          name: "PendingDispute",
          inputs: [],
        },
        {
          type: "error",
          name: "ProofMismatch",
          inputs: [],
        },
        {
          type: "error",
          name: "RateLimited",
          inputs: [],
        },
        {
          type: "error",
          name: "Reentrancy",
          inputs: [],
        },
        {
          type: "error",
          name: "ResponseWindowClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "RevealWindowClosed",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SlashCooldownActive",
          inputs: [],
        },
        {
          type: "error",
          name: "TwapStale",
          inputs: [],
        },
        {
          type: "error",
          name: "UnknownRegistration",
          inputs: [],
        },
        {
          type: "error",
          name: "WrongDisputeState",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 47165937,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
